//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W3Devices.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("W3Devices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A double click onto the cell opens an editor{0}window for the device&apos;s repairs field ähnelt.
        /// </summary>
        internal static string ADoubleClickOntoTheCellOpensAnEditorNwindowForTheDeviceSRepairsField {
            get {
                return ResourceManager.GetString("ADoubleClickOntoTheCellOpensAnEditorNwindowForTheDeviceSRepairsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all groups ähnelt.
        /// </summary>
        internal static string AllGroups {
            get {
                return ResourceManager.GetString("AllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Api-Key ähnelt.
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Key Required ähnelt.
        /// </summary>
        internal static string APIKeyRequired {
            get {
                return ResourceManager.GetString("APIKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API key saved successfully ähnelt.
        /// </summary>
        internal static string APIKeySavedSuccessfully {
            get {
                return ResourceManager.GetString("APIKeySavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API rate limit exceeded. Please try again later ähnelt.
        /// </summary>
        internal static string APIRateLimitExceededPleaseTryAgainLater {
            get {
                return ResourceManager.GetString("APIRateLimitExceededPleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die W3Devices ähnelt.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery ähnelt.
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charging ähnelt.
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear search text and reset devices ähnelt.
        /// </summary>
        internal static string ClearSearchTextAndResetDevices {
            get {
                return ResourceManager.GetString("ClearSearchTextAndResetDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Connection ähnelt.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device Count by Group ähnelt.
        /// </summary>
        internal static string DeviceCountByGroup {
            get {
                return ResourceManager.GetString("DeviceCountByGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device name ähnelt.
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device report for {0} from {1} ähnelt.
        /// </summary>
        internal static string DeviceReportFor0From1 {
            get {
                return ResourceManager.GetString("DeviceReportFor0From1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Devices list from {0} ähnelt.
        /// </summary>
        internal static string DevicesListFrom0 {
            get {
                return ResourceManager.GetString("DevicesListFrom0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string DevName {
            get {
                return ResourceManager.GetString("DevName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit {0} for {1} ähnelt.
        /// </summary>
        internal static string Edit0 {
            get {
                return ResourceManager.GetString("Edit0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error deleting cached JSON file:  ähnelt.
        /// </summary>
        internal static string ErrorDeletingCachedJSONFile {
            get {
                return ResourceManager.GetString("ErrorDeletingCachedJSONFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error fetching and displaying devices ähnelt.
        /// </summary>
        internal static string ErrorFetchingAndDisplayingDevices {
            get {
                return ResourceManager.GetString("ErrorFetchingAndDisplayingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error fetching data:  ähnelt.
        /// </summary>
        internal static string ErrorFetchingData {
            get {
                return ResourceManager.GetString("ErrorFetchingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error fetching devices ähnelt.
        /// </summary>
        internal static string ErrorFetchingDevices {
            get {
                return ResourceManager.GetString("ErrorFetchingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error fetching devices from cache:  ähnelt.
        /// </summary>
        internal static string ErrorFetchingDevicesFromCache {
            get {
                return ResourceManager.GetString("ErrorFetchingDevicesFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error parsing JSON:  ähnelt.
        /// </summary>
        internal static string ErrorParsingJSON {
            get {
                return ResourceManager.GetString("ErrorParsingJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error saving devices to cache:  ähnelt.
        /// </summary>
        internal static string ErrorSavingDevicesToCache {
            get {
                return ResourceManager.GetString("ErrorSavingDevicesToCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exported displayed devices to SQLite database. ähnelt.
        /// </summary>
        internal static string ExportedDisplayedDevicesToSQLiteDatabase {
            get {
                return ResourceManager.GetString("ExportedDisplayedDevicesToSQLiteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Successful ähnelt.
        /// </summary>
        internal static string ExportSuccessful {
            get {
                return ResourceManager.GetString("ExportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fetch devices from Scalefusion cloud ähnelt.
        /// </summary>
        internal static string FetchDevicesFromScalefusionCloud {
            get {
                return ResourceManager.GetString("FetchDevicesFromScalefusionCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GroupName ähnelt.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load devices ähnelt.
        /// </summary>
        internal static string LoadDevices {
            get {
                return ResourceManager.GetString("LoadDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Location ähnelt.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model ähnelt.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No cached data found. ähnelt.
        /// </summary>
        internal static string NoCachedDataFound {
            get {
                return ResourceManager.GetString("NoCachedDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No devices found. ähnelt.
        /// </summary>
        internal static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Acceptable ähnelt.
        /// </summary>
        internal static string NotAcceptable {
            get {
                return ResourceManager.GetString("NotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Found ähnelt.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your API key and save it before fetching data. ähnelt.
        /// </summary>
        internal static string PleaseEnterYourAPIKeyAndSaveItBeforeFetchingData {
            get {
                return ResourceManager.GetString("PleaseEnterYourAPIKeyAndSaveItBeforeFetchingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait while fetching device data... ähnelt.
        /// </summary>
        internal static string PleaseWaitWhileFetchingDeviceData {
            get {
                return ResourceManager.GetString("PleaseWaitWhileFetchingDeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error:  ähnelt.
        /// </summary>
        internal static string PrintError {
            get {
                return ResourceManager.GetString("PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rate limit exceeded ähnelt.
        /// </summary>
        internal static string RateLimitExceeded {
            get {
                return ResourceManager.GetString("RateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reload1 {
            get {
                object obj = ResourceManager.GetObject("reload1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remarks ähnelt.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Renew ähnelt.
        /// </summary>
        internal static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repairs ähnelt.
        /// </summary>
        internal static string Repairs {
            get {
                return ResourceManager.GetString("Repairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request not acceptable. Please check your request headers and try again. ähnelt.
        /// </summary>
        internal static string RequestNotAcceptablePleaseCheckYourRequestHeadersAndTryAgain {
            get {
                return ResourceManager.GetString("RequestNotAcceptablePleaseCheckYourRequestHeadersAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resource not found. Please verify the API URL and try again. ähnelt.
        /// </summary>
        internal static string ResourceNotFoundPleaseVerifyTheAPIURLAndTryAgain {
            get {
                return ResourceManager.GetString("ResourceNotFoundPleaseVerifyTheAPIURLAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save and Exit ähnelt.
        /// </summary>
        internal static string SaveAndExit {
            get {
                return ResourceManager.GetString("SaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save API key to registry ähnelt.
        /// </summary>
        internal static string SaveAPIKeyToRegistry {
            get {
                return ResourceManager.GetString("SaveAPIKeyToRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save device report to pdf ähnelt.
        /// </summary>
        internal static string SaveDeviceReportToPdf {
            get {
                return ResourceManager.GetString("SaveDeviceReportToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search in all devices ähnelt.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search in all devices ähnelt.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serial ähnelt.
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serial2 ähnelt.
        /// </summary>
        internal static string Serial2 {
            get {
                return ResourceManager.GetString("Serial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serial number ähnelt.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show devices by group ähnelt.
        /// </summary>
        internal static string ShowDevicesByGroup {
            get {
                return ResourceManager.GetString("ShowDevicesByGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sqlite-Export ähnelt.
        /// </summary>
        internal static string SqliteExport {
            get {
                return ResourceManager.GetString("SqliteExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unauthorized ähnelt.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unauthorized access. Please check your API key and try again. ähnelt.
        /// </summary>
        internal static string UnauthorizedAccessPleaseCheckYourAPIKeyAndTryAgain {
            get {
                return ResourceManager.GetString("UnauthorizedAccessPleaseCheckYourAPIKeyAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon w3coach {
            get {
                object obj = ResourceManager.GetObject("w3coach", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have reached the maximum API calls per day limit. ähnelt.
        /// </summary>
        internal static string YouHaveReachedTheMaximumAPICallsPerDayLimit {
            get {
                return ResourceManager.GetString("YouHaveReachedTheMaximumAPICallsPerDayLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have reached the maximum API calls per minute limit. ähnelt.
        /// </summary>
        internal static string YouHaveReachedTheMaximumAPICallsPerMinuteLimit {
            get {
                return ResourceManager.GetString("YouHaveReachedTheMaximumAPICallsPerMinuteLimit", resourceCulture);
            }
        }
    }
}
